2022-04-21 23:04:36,316 ERROR: Exception on /user/Tiago [GET] [in c:\users\t\desktop\goodbrowsergames\venv\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "c:\users\t\desktop\goodbrowsergames\venv\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\t\desktop\goodbrowsergames\venv\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\t\desktop\goodbrowsergames\venv\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\t\desktop\goodbrowsergames\venv\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "c:\users\t\desktop\goodbrowsergames\venv\lib\site-packages\flask_login\utils.py", line 277, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Users\T\Desktop\GoodBrowserGames\app\routes.py", line 81, in user
    return render_template('user.html', user=user, posts=posts)
  File "c:\users\t\desktop\goodbrowsergames\venv\lib\site-packages\flask\templating.py", line 148, in render_template
    return _render(
  File "c:\users\t\desktop\goodbrowsergames\venv\lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "c:\users\t\desktop\goodbrowsergames\venv\lib\site-packages\jinja2\environment.py", line 1291, in render
    self.environment.handle_exception()
  File "c:\users\t\desktop\goodbrowsergames\venv\lib\site-packages\jinja2\environment.py", line 926, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\T\Desktop\GoodBrowserGames\app\templates\user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\T\Desktop\GoodBrowserGames\app\templates\base.html", line 30, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\T\Desktop\GoodBrowserGames\app\templates\user.html", line 13, in block 'content'
    {{ form.hidden_tag() }}
  File "c:\users\t\desktop\goodbrowsergames\venv\lib\site-packages\jinja2\environment.py", line 475, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2022-04-21 23:06:53,128 INFO: Microblog startup [in C:\Users\T\Desktop\GoodBrowserGames\app\__init__.py:45]
2022-04-24 21:02:22,728 INFO: Microblog startup [in C:\Users\T\Desktop\GoodBrowserGames\app\__init__.py:45]
2022-04-24 21:05:17,170 INFO: Microblog startup [in C:\Users\T\Desktop\GoodBrowserGames\app\__init__.py:45]
2022-04-24 21:12:05,094 INFO: Microblog startup [in C:\Users\T\Desktop\GoodBrowserGames\app\__init__.py:45]
2022-04-24 21:19:46,778 INFO: Microblog startup [in C:\Users\T\Desktop\GoodBrowserGames\app\__init__.py:45]
